# nixpacks.toml

[phases.setup]
nixPkgs = ['nodejs-18_x','yarn']

[phases.install]
cmds = ['yarn install']

[phases.build]
cmds = ['yarn build']

[start]
cmd = 'cd build && yarn install --production && node server.js'