# nixpacks.toml

[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm install -g yarn','yarn install']

[phases.build]
cmds = ['yarn build']

[start]
cmd = 'cd build && node server.js'